heat_template_version: 2014-10-16

parameters:

  overcloud_flavor:
    type: string

  overcloud_image:
    type: string

  key_name:
    type: string

  overcloud_name:
    type: string

  private_net_admin:
    type: string

  private_net_cluster:
    type: string

  overcloud_user_data:
    type: string

  sg:
    type: string

  # requires ocata
  #tags:
  #  type: string

resources:

  overcloud_node:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: overcloud_flavor}
      image: {get_param: overcloud_image}
      config_drive: false
      key_name: {get_param: key_name}
      user_data_format: SOFTWARE_CONFIG
      networks:
        - {network: {get_param: private_net_admin}}
        - {network: {get_param: private_net_cluster}}
      security_groups:
        - "default"
        - {get_param: sg}
      name: {get_param: overcloud_name}
      software_config_transport: POLL_SERVER_HEAT
      user_data: {get_param: overcloud_user_data}
      #tags: {get_param: tags}

outputs:

  overcloud_node:
    description: "overcloud node resource"
    value: {get_resource: overcloud_node}
  overcloud_private_ip:
    description: "private admin ip of the overcloud instance"
    value:
      get_attr:
        - overcloud_node
        - networks
        - {get_param: private_net_admin}
        - 0
