heat_template_version: 2015-04-30

# Template which provides a private network for a cluster.
# This template just passes through the name of an already created
# private networks.

parameters:

  private_net_cluster:
    type: string
    description: Name of private network for cluster management et al

outputs:
  private_net_cluster:
    value: {get_param: private_net_cluster}
