heat_template_version: 2015-04-30

# Template which provides a private networks for admin/control, which is
# routed to an external network.
# This template just passes through the name of an already created
# private networks.
# Expects a pre-created router, network and a subnet with CIDR 192.168.0.0/24.

parameters:

  private_net_admin:
    default: private
    type: string
  private_subnet_admin:
    default: private
    type: string

outputs:
  private_net_admin:
    value: {get_param: private_net_admin}
  private_subnet_admin:
    value: {get_param: private_subnet_admin}
