heat_template_version: 2015-04-30

parameters:

  overcloud_flavor:
    type: string
    default: overcloud
    description: Nova flavor for overcloud instances. Recommended to be at least 4
                 vcpu, 8 GB RAM, 40 GB disk

  overcloud_image:
    type: string
    default: empty
    description: The base image to use for overcloud instances

  key_name:
    type: string
    default: default
    description: Nova keypair to inject into the undercloud and overcloud instances

  controller_node_count:
    type: number
    default: 1
    description: Number of controller overcloud instances to deploy

  compute_node_count:
    type: number
    default: 1
    description: Number of compute overcloud instances to deploy

  private_net:
    type: string
    default: private
    description: Name of a private network which will be associated with all instances

  public_net:
    type: string
    default: public
    description: Name of the network to use for allocating a floating ip for the undercloud instance

  overcloud_name:
    type: string
    default: overcloud
    description: Name of the overcloud instances. The name will be prefixed with the stack name.

  undercloud_name:
    type: string
    default: undercloud
    description: Name of the undercloud instance. The name will be prefixed with the stack name.

  undercloud_flavor:
    type: string
    default: m1.large
    description: Nova flavor for the undercloud instance. Recommended to be at least 4
                 vcpu, 8 GB RAM, 40 GB disk

  undercloud_image:
    type: string
    default: CentOS-7-x86_64-GenericCloud-1503
    description: Image to boot as the undercloud instance


resources:

  public_network:
    type: OS::TraaS::PublicNetwork
    properties:
      public_net: {get_param: public_net}

  private_network:
    type: OS::TraaS::PrivateNetwork
    properties:
      private_net: {get_param: private_net}

  user_data_script:
    type: OS::Heat::Value
    properties:
      type: string
      value: |
        #!/bin/bash
        rpm -q git || yum -y install git
        git clone https://git.openstack.org/openstack-infra/tripleo-ci
        export HOME=/root
        tripleo-ci/scripts/tripleo.sh --repo-setup
        yum -y install python-heat-agent*
        systemctl daemon-reload
        systemctl enable os-collect-config
        systemctl start os-collect-config
        sudo setenforce 0

  undercloud:
    depends_on: [public_network]
    type: OS::TraaS::Undercloud
    properties:
      undercloud_flavor: {get_param: undercloud_flavor}
      undercloud_image: {get_param: undercloud_image}
      key_name: {get_param: key_name}
      undercloud_name:
        list_join:
          - '-'
          - - {get_param: 'OS::stack_name'}
            - {get_param: undercloud_name}
      undercloud_user_data: {get_attr: [user_data_script, value]}
      private_net: {get_attr: [private_network, private_net]}
      public_net: {get_attr: [public_network, public_net]}

  overcloud_nodes:
    type: OS::TraaS::OvercloudNodes
    depends_on: [private_network]
    properties:
      overcloud_flavor: {get_param: overcloud_flavor}
      overcloud_image: {get_param: overcloud_image}
      key_name: {get_param: key_name}
      controller_node_count: {get_param: controller_node_count}
      compute_node_count: {get_param: compute_node_count}
      private_net: {get_attr: [private_network, private_net]}
      overcloud_user_data: {get_attr: [user_data_script, value]}
      overcloud_name:
        list_join:
          - '-'
          - - {get_param: 'OS::stack_name'}
            - {get_param: overcloud_name}

  oooq_job:
    type: OS::TraaS::OooqJob
    depends_on: [undercloud, overcloud_nodes]
    properties:
      undercloud: {get_attr: [undercloud, undercloud_server]}
      undercloud_private_ip: {get_attr: [undercloud, undercloud_private_ip]}
      overcloud_nodes:
        map_merge:
          - get_attr: [overcloud_nodes, resource.controller_overcloud_nodes, attributes, overcloud_node]
          - get_attr: [overcloud_nodes, resource.compute_overcloud_nodes, attributes, overcloud_node]
      controller_private_ips: {get_attr: [overcloud_nodes, resource.controller_overcloud_nodes, overcloud_private_ip]}
      compute_private_ips: {get_attr: [overcloud_nodes, resource.compute_overcloud_nodes, overcloud_private_ip]}


outputs:
  controller_private_ips:
    description: multinode CONTROLLER_IPS param for oooq
    value:
      list_join:
        - ' '
        - {get_attr: [overcloud_nodes, resource.controller_overcloud_nodes, overcloud_private_ip]}
  compute_private_ips:
    description: multinode COMPUTE_IPS param for oooq
    value:
      list_join:
        - ' '
        - {get_attr: [overcloud_nodes, resource.compute_overcloud_nodes, overcloud_private_ip]}
